###
GET http://localhost:4001/

###
get http://localhost:4001/profile/heartbeat


###
GET http://localhost:4001/api/v1/profile/info/1001

###
POST http://localhost:4001/api/v1/profile/forgotPassword
Content-Type: application/json

{
    "emailAddress":"GD@gmail.com"
}

###
POST http://localhost:4001/api/v1/profile/register
Content-Type: application/json

{
  "emailAddress": "rahufdgdsl@gmail.com",
  "password": "1234567890aA&",
  "firstName": "Rahul",
  "lastName": "Raghunath",
  "profileType":"1"
}

###
PUT http://localhost:4001/api/v1/profile/verifyEmail/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMTYsImlhdCI6MTcxMDEwNDAxMiwiZXhwIjoxNzEwMTA0NjEyLCJ0eXBlIjo0fQ.rxjB2sxi6FqVxDWlg9GaV3FaJJh5WwVSNbbrhJEMwTk
Content-Type: application/json

###
POST http://localhost:4001/api/v1/profile/regenerateVerifyEmail/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMTUsImlhdCI6MTcxMDEwMjkzOSwiZXhwIjoxNzEwMTAzNTM5LCJ0eXBlIjo0fQ.lQ1IIzWVCvNt3f0_eONp9UAk96ZmCrZ5G551cXT01EI
Content-Type: application/json



###
POST http://localhost:4001/api/v1/profile/login
Content-Type: application/json

{
    "email":"ur@gmail.com",
    "password": "1234567890aA&"
}

###
POST http://localhost:4001/api/v1/profile/forgotChangePassword/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwMTAsImlhdCI6MTcwOTEyNTIwOSwiZXhwIjoxNzA5MjExNjA5LCJ0eXBlIjo1fQ.caay3mYZrHT7eT9bkXSsLC-Iezc12WlySD8DH3fkmzE
Content-Type: application/json

{
        "newPassword":"1234567890aA&change",
        "confirmPassword":"1234567890aA&change"
}

###
GET  http://localhost:4001/api/v1/campaigns

###
POST  http://localhost:4001/api/v1/campaigns
Content-Type: application/json

{ 
     "CampaignName":"Campaign Name",
      "Description":"Akhil loves devika",
      "TargetAmount":"5000",
      "CampaignEndDate" : "2024-02-15 15:30:45"
}

###
POST  http://localhost:4001/api/v1/register
Content-Type: application/json

{ 
  "email": "rahufdgdsl@gmail.com",
  "password": "1234567890aA&"
}

###
POST  http://localhost:4001/api/v1/login
Content-Type: application/json

{ 
  "email": "rahufdgdsl@gmail.com",
  "password": "1234567890aA&"
}

###
POST  http://localhost:4001/api/v1/order
Content-Type: application/json

{ 
  "Amount": 50000,
  "CampaignID": 1

}

###
POST  http://localhost:4001/api/v1/order/validate
Content-Type: application/json

{ 
  "amount": 50000,
  "currency": "INR",
  "receipt": "campaignID:"
}